name: nothrow
favicon: null
layout_spectrum: 0.7624294296838343
typography_spectrum: 0.6190991553012282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48987613385543227
  lightness: 0.4933223966509104
  saturation: 0.6339772988576442
  rhythmicContrast: 0.6539052126463503
purpose: []
